version: '3.9'

services:
  nostressgo:
    container_name: nostressgo
    environment:
      - PGUSER=${PGUSER:-pguser}
      - PGPASSWORD=${PGPASSWORD:-pgpass}
      - PGDATABASE=${PGDATABASE:-nostressgo}
      - PGHOST=${PGHOST:-nostressgo-db}
      - PGPORT=${PGPORT:-5432}
    tty: true
    build: .
    ports:
      - ${NOSTRESSGO_PORT}:${NOSTRESSGO_PORT}
    restart: on-failure
    depends_on:
      - nostressgo-db
  

  nostressgo-db:
    image: postgres:latest
    container_name: nostressgo-db
    environment:
      - PGUSER=${PGUSER:-pguser}
      - PGPASSWORD=${PGPASSWORD:-pgpass}
      - PGDATABASE=${PGDATABASE:-nostressgo}
      - PGHOST=${PGHOST:-nostressgo-db}
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    ports:
      - '${PGPORT:-5432}:${PGPORT:-5432}'
