version: '3'

services:
  nostressgo:
    container_name: nostressgo
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pgpass}
      - POSTGRES_DB=${POSTGRES_DB:-nostressgo}
      - POSTGRES_HOST=${POSTGRES_HOST:-nostressgo-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
    tty: true
    build: .
    ports:
      - ${NOSTRESSGO_PORT}:${NOSTRESSGO_PORT}
    restart: unless-stopped
    depends_on:
      - nostressgo-db
  
  nostressgo-db:
    image: postgres:latest
    restart: unless-stopped
    container_name: nostressgo-db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pgpass}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-nostressgo}
      - POSTGRES_HOST=${POSTGRES_HOST:-nostressgo-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      # PGDATA is important to avoid permission issues when mounting
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}'
  
  nostressgo-pgadmin:
    image: dpage/pgadmin4
    container_name: nostressgo-pgadmin
    restart: always
    ports:
      - '${PGADMIN_PORT:-8888}:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-test@test.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-pgpass}
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    depends_on:
      - nostressgo-db

networks:
  default:
    external:
      name: proxy